version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: db_logistica
    restart: always
    environment:
      POSTGRES_USER: admin_api
      POSTGRES_PASSWORD: dUiZBmHsbLWG2HiV4zx3eFYn0W7hpyQ2xhdRI5v3U49cWV9kkIW
      POSTGRES_DB: logistica_db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistica_net

  api:
    build: .
    container_name: api_logistica
    depends_on:
      - db
    ports:
      - "8282:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://admin_api:dUiZBmHsbLWG2HiV4zx3eFYn0W7hpyQ2xhdRI5v3U49cWV9kkIW@db:5432/logistica_db
      PYTHONPATH: /code
      SECRET_KEY: 2a12xVtfIpePbkrohfumSDBedzcOFbEaKDOsTcdqYDTIYfk8FOIqe
      ACCESS_TOKEN_EXPIRE_MINUTES: '120'
      JWT_ALGORITHM: HS256
      INITIAL_USER: integracao_logistica
      INITIAL_PASSWORD: Integracao@123Senha
      CLIENT_USER: '09098221000380'
      CLIENT_PASSWORD: 'SBF68686fohjbhc7CUJS88IC9vsefhbs9'
      BRUDAM_CLIENTE: '09098221000542'
      BRUDAM_USUARIO: 659622e0526337fd21fb894cb24a72ee
      BRUDAM_SENHA: 843c6e949059ec5040e62ad7330959981d3e505e90146e8be15f2ec0f1fa16d7
      BRUDAM_URL_LOGIN: https://api.brudam.com.br/services/auth/login
      BRUDAM_URL_TRACKING: https://homosbf.brudam.com.br/api/v1/tracking/ocorrencias
      BRUDAM_URL_UPLOAD_CTE: https://api.brudam.com.br/services/dfe/cte/upload
    volumes:
      - .:/code
    command: ["./docker-entrypoint.sh"]
    networks:
      - logistica_net

networks:
  logistica_net:
    driver: bridge

volumes:
  postgres_data: