version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_logistica
    restart: always
    environment:
      POSTGRES_USER: admin_api
      POSTGRES_PASSWORD: dUiZBmHsbLWG2HiV4zx3eFYn0W7hpyQ2xhdRI5v3U49cWV9kkIW
      POSTGRES_DB: logistica_db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistica_net

  api:
    build: .
    container_name: api_logistica
    depends_on:
      - db
    ports:
      - "8282:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://admin_api:dUiZBmHsbLWG2HiV4zx3eFYn0W7hpyQ2xhdRI5v3U49cWV9kkIW@db:5432/logistica_db
      PYTHONPATH: /code
      SECRET_KEY: $2a$12$xVtfI/pePb.krohfumSDBedzcOF/bEaKDOsTcdqYDTIY.fk8FOIqe
      ACCESS_TOKEN_EXPIRE_MINUTES: '120'
      JWT_ALGORITHM: HS256
      INITIAL_USER: integracao_logistica
      INITIAL_PASSWORD: Integracao@123Senha
      CLIENT_USER: '09098221000380'
      CLIENT_PASSWORD: 'JpY7HMVz2tMQeF04pxmTaMT09DtQyG'
    volumes:
      - .:/code
    command: ["./docker-entrypoint.sh"]
    networks:
      - logistica_net

networks:
  logistica_net:
    driver: bridge

volumes:
  postgres_data: